name: Lint, Test, Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: yarn
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            packages/neo-nano-ui/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles( '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles( '**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test
      - name: Build with Next.js
        run: yarn build
